[target.x86_64-unknown-linux-musl]

linker = "x86_64-linux-musl-gcc"

rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-static"]

  

[target.aarch64-unknown-linux-musl]

linker = "aarch64-linux-musl-gcc-ld"

rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-static"]

  

[target.x86_64-pc-windows-gnu]

linker = "x86_64-w64-mingw32-gcc"

rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-static"]
